sudo: required
service:
  - docker

before_install:
  - docker build -t letrungviet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true letrungviet/react-test npm run test -- --coverage

after_success:
  - docker build -t letrungviet/multi-client ./client
  - docker build -t letrungviet/multi-nginx ./nginx
  - docker build -t letrungviet/multi-server ./server
  - docker build -t letrungviet/multi-worker ./worker

#login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push letrungviet/multi-client
  - docker push letrungviet/multi-nginx
  - docker push letrungviet/multi-server
  - docker push letrungviet/multi-worker
  
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker"
#  env: "Docker-env"
#  bucker_name: "elasticbeanstalk-us-east-2-883158296135"
#  bucker_path: "path"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: "$AWS_SECRET_KEY"

